#!/usr/bin/env python3
"""Synthetic en_US.utf8 PG17/PostGIS3.5 forward/restore checks; hosted CI only."""
from __future__ import annotations
import argparse
import hashlib
from datetime import datetime, timedelta, timezone
import json
import math
import os
from pathlib import Path
import re
import subprocess
import sys
import time
import uuid

LOCALE = 'en_US.utf8'
OLD_SERVER, NEW_SERVER = 170005, 170011
OLD_POSTGIS, NEW_POSTGIS = '3.5.2', '3.5.7'
OLD_TEXT = ['가', '각', '나', '한글', '서울', 'A', 'a', 'Z', 'z', 'é', 'e\u0301',
            'e', 'E', 'Å', 'A\u030a', '10', '2', '02', '가1', '가2', '가10', 'ß', 'ss', 'á', 'ä']
NEW_TEXT = ['새글', '한글2', 'B', 'b', 'É', 'e\u0301x', '11', '3']
ROLES = 'CREATE ROLE map_owner NOLOGIN; CREATE ROLE map_runtime LOGIN; CREATE ROLE hub_owner NOLOGIN; CREATE ROLE admin_owner NOLOGIN;'
SEED = """
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
CREATE EXTENSION pgcrypto;
CREATE SCHEMA user_service AUTHORIZATION map_owner;
CREATE SCHEMA hub_data AUTHORIZATION hub_owner;
CREATE SCHEMA admin_control AUTHORIZATION admin_owner;
SET ROLE map_owner;
CREATE TABLE user_service.fixture (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, payload jsonb NOT NULL, location geometry(Point,4326), captured_at timestamptz NOT NULL, sealed bytea NOT NULL);
INSERT INTO user_service.fixture(payload,location,captured_at,sealed) VALUES ('{"synthetic":true,"stage":"old"}',ST_SetSRID(ST_MakePoint(0,0),4326),'2026-01-01T00:00:00Z',pgp_sym_encrypt('map-synthetic-old','map-public-fixture-key','cipher-algo=aes256,compress-algo=0'));
CREATE TABLE user_service.collation_fixture (id integer PRIMARY KEY, value text NOT NULL, stage text NOT NULL CHECK(stage IN ('old','new')));
CREATE UNIQUE INDEX fixture_text_value_key ON user_service.collation_fixture(value) INCLUDE(id,stage);
GRANT USAGE ON SCHEMA user_service TO map_runtime;
GRANT SELECT,INSERT,UPDATE ON ALL TABLES IN SCHEMA user_service TO map_runtime;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA user_service TO map_runtime;
RESET ROLE;
SET ROLE hub_owner;
CREATE TABLE hub_data.fixture(id integer PRIMARY KEY, marker text NOT NULL);
INSERT INTO hub_data.fixture VALUES (1,'synthetic-hub');
RESET ROLE;
SET ROLE admin_owner;
CREATE TABLE admin_control.fixture(id integer PRIMARY KEY, marker text NOT NULL);
INSERT INTO admin_control.fixture VALUES (1,'synthetic-admin');
RESET ROLE;
"""
CIPHERTEXT_PROBE = """SELECT json_build_object(
 'rows',count(*),
 'decrypt_matches',bool_and(pgp_sym_decrypt(sealed,'map-public-fixture-key')='map-synthetic-'||(payload->>'stage')),
 'not_plaintext',bool_and(sealed<>convert_to('map-synthetic-'||(payload->>'stage'),'UTF8')),
 'symmetric_packet',bool_and(pgp_key_id(sealed)='SYMKEY'),
 'ciphertext_sha256',encode(digest(string_agg(encode(sealed,'hex'),'' ORDER BY id),'sha256'),'hex'))
 FROM user_service.fixture;"""


def validate_ciphertext(observed):
    require(type(observed.get('rows')) is int and observed['rows'] in (1, 2), 'ciphertext_row_count')
    require(all(observed.get(key) is True for key in ('decrypt_matches', 'not_plaintext', 'symmetric_packet')),
            'ciphertext_roundtrip_mismatch')
    require(re.fullmatch(r'[0-9a-f]{64}', observed.get('ciphertext_sha256', '')), 'ciphertext_digest_missing')


SNAPSHOT = """SELECT json_build_object(
 'rows',(SELECT json_agg(json_build_object('id',id,'payload',payload,'wkt',ST_AsEWKT(location),'captured_at',captured_at,'sealed',encode(sealed,'hex')) ORDER BY id) FROM user_service.fixture),
 'text',(SELECT json_agg(json_build_object('id',id,'value',value,'utf8',encode(convert_to(value,'UTF8'),'hex'),'stage',stage) ORDER BY id) FROM user_service.collation_fixture),
 'hub',(SELECT json_agg(row_to_json(x)) FROM (SELECT * FROM hub_data.fixture ORDER BY id) x),
 'admin',(SELECT json_agg(row_to_json(x)) FROM (SELECT * FROM admin_control.fixture ORDER BY id) x),
 'owners',(SELECT json_agg(row_to_json(x)) FROM (SELECT schemaname,tablename,tableowner FROM pg_tables WHERE schemaname IN ('user_service','hub_data','admin_control') ORDER BY schemaname,tablename) x),
 'runtime',(SELECT json_build_object('select',has_table_privilege('map_runtime','user_service.fixture','SELECT'),'insert',has_table_privilege('map_runtime','user_service.fixture','INSERT'),'schema_create',has_schema_privilege('map_runtime','user_service','CREATE'),'hub_schema',has_schema_privilege('map_runtime','hub_data','USAGE'),'admin_schema',has_schema_privilege('map_runtime','admin_control','USAGE'),'superuser',rolsuper,'create_db',rolcreatedb,'create_role',rolcreaterole,'replication',rolreplication,'bypass_rls',rolbypassrls) FROM pg_roles WHERE rolname='map_runtime')
);"""
META = """SELECT json_build_object('server',current_setting('server_version_num'),
 'postgis',postgis_lib_version(),'postgis_full',postgis_full_version(),
 'pgcrypto_sha256',encode(digest('map-synthetic-pgcrypto','sha256'),'hex'),
 'extensions',(SELECT json_object_agg(extname,extversion) FROM pg_extension),
 'encoding',current_setting('server_encoding'),'collation',datcollate,'ctype',datctype,
 'provider',datlocprovider,'declared_collation_version',datcollversion,
 'actual_collation_version',pg_database_collation_actual_version(oid))
 FROM pg_database WHERE datname=current_database();"""
# Independent fixed geometry answers exercise SFCGAL across both library majors.
# Extensions are loaded in a rolled-back transaction; the preserved dump contract
# and its exact extension inventory remain unchanged.
SFCGAL_PROBE = """BEGIN; SET LOCAL statement_timeout='10s';
CREATE EXTENSION postgis_sfcgal;
WITH cut AS (SELECT CG_3DIntersection(
 'LINESTRING Z (0 0 0,2 0 0)'::geometry,
 'LINESTRING Z (1 0 0,3 0 0)'::geometry) AS geom),
solid AS (SELECT CG_MakeSolid(CG_Extrude(
 'POLYGON ((0 0,1 0,1 1,0 1,0 0))'::geometry,0,0,2)) AS geom)
SELECT json_build_object('sfcgal_version',postgis_sfcgal_version(),
 'intersection_length',ST_3DLength(cut.geom),
 'intersection_dimension',ST_CoordDim(cut.geom),
 'intersection_min_x',ST_XMin(Box3D(cut.geom)),
 'intersection_max_x',ST_XMax(Box3D(cut.geom)),
 'intersection_min_z',ST_ZMin(Box3D(cut.geom)),
 'intersection_max_z',ST_ZMax(Box3D(cut.geom)),
 'solid_volume',CG_Volume(solid.geom)) FROM cut,solid;
ROLLBACK;"""
SFCGAL_ANSWERS = {'intersection_length': 1, 'intersection_dimension': 3,
                  'intersection_min_x': 1, 'intersection_max_x': 2,
                  'intersection_min_z': 0, 'intersection_max_z': 0,
                  'solid_volume': 2}

# Exercise the GDAL runtime through PostGIS itself. Enable only the three fixed
# synthetic formats in this rolled-back fixture transaction; no live setting or
# out-of-database raster is touched. Constant pixels keep JPEG tolerance explicit.
RASTER_PROBE = """BEGIN; SET LOCAL statement_timeout='15s';
CREATE EXTENSION postgis_raster;
SET LOCAL postgis.gdal_enabled_drivers='GTiff PNG JPEG';
SET LOCAL postgis.enable_outdb_rasters=off;
WITH src AS (SELECT ST_AddBand(
 ST_MakeEmptyRaster(2,2,0,0,0.5,-0.5,0,0,4326),1,'8BUI'::text,128,0) AS rast),
encoded AS (SELECT fmt,ST_AsGDALRaster(src.rast,fmt) AS bytes
 FROM src CROSS JOIN unnest(ARRAY['GTiff','PNG','JPEG']) AS fmt),
decoded AS (SELECT fmt,octet_length(bytes) AS encoded_bytes,ST_FromGDALRaster(bytes) AS rast FROM encoded)
SELECT json_build_object('gdal_version',postgis_gdal_version(),
 'formats',(SELECT json_agg(json_build_object('format',fmt,'encoded_bytes',encoded_bytes,
 'width',ST_Width(rast),'height',ST_Height(rast),'bands',ST_NumBands(rast),
 'count',ST_Count(rast,1,true),'pixel_min',(ST_SummaryStats(rast,1,true)).min,
 'pixel_max',(ST_SummaryStats(rast,1,true)).max,'srid',ST_SRID(rast),
 'upper_left_x',ST_UpperLeftX(rast),'upper_left_y',ST_UpperLeftY(rast),
 'scale_x',ST_ScaleX(rast),'scale_y',ST_ScaleY(rast)) ORDER BY fmt) FROM decoded));
ROLLBACK;"""


def validate_raster(observed):
    require(set(observed) == {'gdal_version', 'formats'}
            and isinstance(observed['gdal_version'], str) and observed['gdal_version'].startswith('GDAL '),
            'raster_probe_fields')
    rows = observed['formats']
    require(isinstance(rows, list) and len(rows) == 3
            and {r['format'] for r in rows} == {'GTiff', 'PNG', 'JPEG'}, 'raster_formats_required')
    for row in rows:
        require(type(row['encoded_bytes']) is int and row['encoded_bytes'] > 0, 'raster_empty_encoding')
        for key, value in {'width': 2, 'height': 2, 'bands': 1, 'count': 4}.items():
            require(type(row[key]) is int and row[key] == value, 'raster_' + key + '_mismatch')
        for key in ('pixel_min', 'pixel_max'):
            value = row[key]
            require(type(value) in (int, float) and math.isfinite(value)
                    and abs(value - 128) <= (1 if row['format'] == 'JPEG' else 0), 'raster_pixel_mismatch')
        if row['format'] == 'GTiff':
            for key, expected in {'srid': 4326, 'upper_left_x': 0, 'upper_left_y': 0,
                                  'scale_x': 0.5, 'scale_y': -0.5}.items():
                value = row[key]
                require(type(value) in (int, float) and math.isfinite(value)
                        and abs(value - expected) <= 1e-9, 'raster_georeference_mismatch')


def validate_sfcgal(observed):
    require(set(observed) == {'sfcgal_version', *SFCGAL_ANSWERS}, 'sfcgal_probe_fields')
    require(isinstance(observed['sfcgal_version'], str)
            and re.fullmatch(r'[0-9]+\.[0-9]+\.[0-9]+(?:[ +.-][A-Za-z0-9.+_-]+)?', observed['sfcgal_version']),
            'sfcgal_runtime_version_missing')
    for name, expected in SFCGAL_ANSWERS.items():
        value = observed[name]
        require(type(value) in (int, float) and math.isfinite(value)
                and abs(value - expected) <= 1e-9, 'sfcgal_' + name + '_mismatch')


EXPECTED_ACL = {'select': True, 'insert': True, 'schema_create': False, 'hub_schema': False,
                'admin_schema': False, 'superuser': False, 'create_db': False,
                'create_role': False, 'replication': False, 'bypass_rls': False}
QUERY_FILTERS = {'order': '', 'range': " WHERE value >= 'A' AND value < 'z'", 'equality': " WHERE value = 'é'"}
OWNER_PATHS = ['/var/lib/postgresql/data', '/var/lib/postgresql/data/base',
               '/var/lib/postgresql/data/global', '/var/lib/postgresql/data/pg_wal']
PHASES = ['baseline', 'forward_restore', 'new_writes', 'candidate_restart', 'post_upgrade_backup',
          'old_pre_upgrade_backup_restore', 'old_post_upgrade_logical_restore']


def require(value, message):
    if not value:
        raise ValueError(message)


def digest(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True, ensure_ascii=False).encode()).hexdigest()


def text_insert(values, stage, offset):
    # This helper accepts the fixed synthetic corpus only, not runtime/user data.
    require(stage in ('old', 'new') and values == (OLD_TEXT if stage == 'old' else NEW_TEXT), 'synthetic_corpus_required')
    rows = ','.join("(%d,'%s','%s')" % (offset + i, value.replace("'", "''"), stage) for i, value in enumerate(values, 1))
    return 'INSERT INTO user_service.collation_fixture VALUES ' + rows + ';'


def validate_runtime(meta, stage):
    require(stage in ('old', 'new'), 'runtime_stage')
    require(int(meta['server']) == (OLD_SERVER if stage == 'old' else NEW_SERVER), 'exact_' + stage + '_postgres_version')
    expected = OLD_POSTGIS if stage == 'old' else NEW_POSTGIS
    require(meta['postgis'] == expected, 'exact_' + stage + '_postgis_library')
    require(set(meta['extensions']) == {'plpgsql', 'postgis', 'postgis_topology', 'pgcrypto'}, 'extension_set_changed')
    require(meta['extensions']['postgis'] == expected and meta['extensions']['postgis_topology'] == expected, 'postgis_catalog_library_mismatch')
    require(meta['pgcrypto_sha256'] == hashlib.sha256(b'map-synthetic-pgcrypto').hexdigest(), 'pgcrypto_runtime_digest_mismatch')
    require(meta['encoding'] == 'UTF8' and meta['collation'] == meta['ctype'] == LOCALE and meta['provider'] == 'c', 'actual_glibc_locale_contract')
    require(bool(meta['declared_collation_version']) and meta['declared_collation_version'] == meta['actual_collation_version'], 'collation_catalog_version_mismatch')
    require(re.fullmatch(r'glibc [0-9]+\.[0-9]+(?:\.[0-9]+)?', meta['glibc']), 'glibc_runtime_required')
    require(meta['process_uid'] == meta['process_gid'] == [999, 999, 999, 999], 'postgres_process_uid_gid_999')
    require(meta['account_uid'] == meta['account_gid'] == '999', 'postgres_account_uid_gid_999')
    require(set(meta['owners']) == set(OWNER_PATHS), 'data_owner_paths_missing')
    require(all(value.split(':')[:2] == ['999', '999'] for value in meta['owners'].values()), 'data_owner_uid_gid_changed')


def plan_nodes(plan):
    yield plan
    for child in plan.get('Plans', []):
        yield from plan_nodes(child)


def validate_query_pair(sequential, indexed, seq_plan, index_plan):
    require(sequential == indexed, 'index_sequential_query_mismatch')
    require(any(p.get('Node Type') == 'Seq Scan' and p.get('Actual Loops', 0) > 0 for p in plan_nodes(seq_plan)), 'sequential_plan_not_executed')
    require(any(p.get('Node Type') in ('Index Scan', 'Index Only Scan') and p.get('Index Name') == 'fixture_text_value_key'
                and p.get('Actual Loops', 0) > 0 for p in plan_nodes(index_plan)), 'expected_btree_plan_not_executed')


def compare_collation(before, after, *, old_cohort=False):
    def rows(report, key):
        values = report['queries'][key]['rows']
        return [r for r in values if r['stage'] == 'old'] if old_cohort else values
    order_before, order_after = rows(before, 'order'), rows(after, 'order')
    membership = lambda values: sorted((r['id'], r['value'], r['stage']) for r in values)
    same_data = membership(order_before) == membership(order_after)
    return {'same_corpus': same_data, 'ordering_changed': order_before != order_after,
            'range_membership_changed': membership(rows(before, 'range')) != membership(rows(after, 'range')),
            'equality_membership_changed': membership(rows(before, 'equality')) != membership(rows(after, 'equality')),
            'before_sha256': digest({k: rows(before, k) for k in QUERY_FILTERS}),
            'after_sha256': digest({k: rows(after, k) for k in QUERY_FILTERS})}


class CommandFailure(RuntimeError):
    def __init__(self, args, returncode, stdout=b'', stderr=b''):
        super().__init__('synthetic_command_failed:' + Path(args[0]).name)
        self.diagnostic = {'tool': Path(args[0]).name, 'operation': args[1] if len(args) > 1 else '',
                           'returncode': returncode, 'synthetic_stdout': stdout.decode(errors='replace')[-4096:],
                           'synthetic_stderr': stderr.decode(errors='replace')[-4096:]}


class Fixture:
    def __init__(self, output):
        self.output = output
        self.token = uuid.uuid4().hex[:12]
        self.containers = []
        self.backups = {}
        self.failures = []
        self.volumes = []

    def run(self, args, *, input=None, accepted=(0,), timeout=120):
        try:
            p = subprocess.run(args, input=input, capture_output=True, timeout=timeout)
        except subprocess.TimeoutExpired as error:
            raise CommandFailure(args, 'timeout', error.stdout or b'', error.stderr or b'') from None
        if p.returncode not in accepted:
            raise CommandFailure(args, p.returncode, p.stdout, p.stderr)
        return p

    def sql(self, name, sql, *, database='fixture', user='postgres', accepted=(0,)):
        return self.run(['docker', 'exec', '-i', name, 'psql', '-h', '127.0.0.1', '-X', '-qAt', '-v', 'ON_ERROR_STOP=1',
                         '-v', 'VERBOSITY=sqlstate', '-U', user, '-d', database], input=sql.encode(), accepted=accepted)

    def ready(self, name, database='postgres'):
        for _ in range(90):
            if self.sql(name, 'SELECT 1;', database=database, accepted=(0, 1, 2)).returncode == 0:
                return
            time.sleep(1)
        raise ValueError('postgres_readiness_timeout')

    def start(self, image, label):
        name = 'map-infra-pg-' + self.token + '-' + label
        volume = name + '-data'
        self.volumes.append(volume)
        expires = (datetime.now(timezone.utc) + timedelta(minutes=150)).isoformat()
        self.run(['docker', 'volume', 'create', '--label', 'map.infra.fixture=' + self.token,
                  '--label', 'map.fixture.expires=' + expires, volume])
        self.containers.append(name)  # Retain even a partly created failed start for owned cleanup.
        self.run(['docker', 'run', '-d', '--name', name, '--label', 'map.infra.fixture=' + self.token,
                  '--label', 'map.fixture.expires=' + expires,
                  '--network', 'none', '--memory', '768m', '--memory-swap', '768m', '--cpus', '1',
                  '--pids-limit', '128', '--log-driver', 'json-file', '--log-opt', 'max-size=10m', '--log-opt', 'max-file=3',
                  '--mount', 'type=volume,src=' + volume + ',dst=/var/lib/postgresql/data',
                  '-e', 'POSTGRES_HOST_AUTH_METHOD=trust',
                  '-e', 'POSTGRES_INITDB_ARGS=--locale=en_US.utf8 --encoding=UTF8', '-e', 'LANG=en_US.utf8', image])
        self.ready(name)
        self.sql(name, ROLES + "CREATE DATABASE fixture TEMPLATE template0 ENCODING 'UTF8' LC_COLLATE 'en_US.utf8' LC_CTYPE 'en_US.utf8';", database='postgres')
        return name

    def stop(self, name):
        self.run(['docker', 'stop', '--time', '30', name], timeout=60)

    def retire(self, name):
        # A completed phase no longer needs a container; retain its bounded
        # synthetic diagnostic and logical dump before normal removal.
        self.stop(name)
        actual = json.loads(self.run(['docker', 'inspect', name]).stdout)[0]
        require(actual['Config'].get('Labels', {}).get('map.infra.fixture') == self.token, 'retire_ownership_mismatch')
        logs = self.run(['docker', 'logs', '--tail', '60', name], accepted=(0, 1))
        (self.output / (name + '-retired.json')).write_text(json.dumps({
            'synthetic_stdout': logs.stdout.decode(errors='replace')[-4096:],
            'synthetic_stderr': logs.stderr.decode(errors='replace')[-4096:]}))
        self.run(['docker', 'rm', name])

    def snapshot(self, name):
        return json.loads(self.sql(name, SNAPSHOT).stdout)

    def metadata(self, name):
        meta = json.loads(self.sql(name, META).stdout)
        meta['glibc'] = self.run(['docker', 'exec', name, 'getconf', 'GNU_LIBC_VERSION']).stdout.decode().strip()
        status = self.run(['docker', 'exec', name, 'cat', '/proc/1/status']).stdout.decode()
        for source, dest in [('Uid', 'process_uid'), ('Gid', 'process_gid')]:
            match = re.search(r'^' + source + r':\s+(\d+)\s+(\d+)\s+(\d+)\s+(\d+)', status, re.M)
            require(match is not None, 'postgres_process_identity_missing')
            meta[dest] = list(map(int, match.groups()))
        for flag, dest in [('-u', 'account_uid'), ('-g', 'account_gid')]:
            meta[dest] = self.run(['docker', 'exec', name, 'id', flag, 'postgres']).stdout.decode().strip()
        owners = self.run(['docker', 'exec', name, 'stat', '-c', '%u:%g:%a', *OWNER_PATHS]).stdout.decode().splitlines()
        require(len(owners) == len(OWNER_PATHS), 'data_owner_stat_incomplete')
        meta['owners'] = dict(zip(OWNER_PATHS, owners))
        return meta

    def sfcgal(self, name):
        observed = json.loads(self.sql(name, SFCGAL_PROBE).stdout)
        validate_sfcgal(observed)
        return observed

    def raster(self, name):
        observed = json.loads(self.sql(name, RASTER_PROBE).stdout)
        validate_raster(observed)
        return observed

    def ciphertext(self, name):
        observed = json.loads(self.sql(name, CIPHERTEXT_PROBE, user='map_runtime').stdout)
        validate_ciphertext(observed)
        return observed

    def collation(self, name):
        report = {'queries': {}, 'index_vs_sequential_verified': False}
        for key, where in QUERY_FILTERS.items():
            query = "SELECT json_build_object('id',id,'value',value,'stage',stage) FROM user_service.collation_fixture" + where + ' ORDER BY value'
            observed = {}
            plans = {}
            for mode in ('sequential', 'index'):
                index = mode == 'index'
                settings = 'SET enable_seqscan=%s; SET enable_indexscan=%s; SET enable_indexonlyscan=%s; SET enable_bitmapscan=off;' % (
                    'off' if index else 'on', 'on' if index else 'off', 'on' if index else 'off')
                observed[mode] = [json.loads(line) for line in self.sql(name, settings + query + ';').stdout.splitlines()]
                plans[mode] = json.loads(self.sql(name, settings + 'EXPLAIN (ANALYZE TRUE, FORMAT JSON, COSTS FALSE, TIMING FALSE, SUMMARY FALSE) ' + query + ';').stdout)[0]['Plan']
            validate_query_pair(observed['sequential'], observed['index'], plans['sequential'], plans['index'])
            report['queries'][key] = {'rows': observed['index'], 'plans': plans}
        report['index_vs_sequential_verified'] = True
        return report

    def denied(self, name, sql, state):
        p = self.sql(name, sql, user='map_runtime', accepted=(0, 3))
        require(p.returncode == 3 and state.encode() in p.stderr, 'expected_sqlstate_' + state + '_missing')

    def probe(self, name, stage, label, result):
        names = ['metadata', 'runtime_acl', 'runtime_ddl_denial', 'hub_denial', 'admin_denial',
                 'unique_constraint', 'negative_probes_preserve_rows', 'btree_sequential_queries', 'sfcgal_geometry_behavior',
                 'raster_gdal_roundtrip', 'ciphertext_roundtrip', 'ciphertext_wrong_key_denial', 'ciphertext_tamper_denial']
        observation = {'checks': {check: 'NOT_RUN' for check in names}}
        result.setdefault('observations', {})[label] = observation

        def observe(check, action):
            try:
                value = action()
                observation['checks'][check] = 'PASS'
                return value
            except Exception:
                observation['checks'][check] = 'FAIL'
                raise

        def metadata():
            meta = self.metadata(name)
            result.setdefault('runtime_observations', {})[label] = meta
            validate_runtime(meta, stage)
            return meta
        meta = observe('metadata', metadata)
        observation['sfcgal'] = observe('sfcgal_geometry_behavior', lambda: self.sfcgal(name))
        require(self.metadata(name)['extensions'] == meta['extensions'], 'sfcgal_transaction_changed_extension_inventory')
        observation['raster'] = observe('raster_gdal_roundtrip', lambda: self.raster(name))
        require(self.metadata(name)['extensions'] == meta['extensions'], 'raster_transaction_changed_extension_inventory')
        observation['ciphertext'] = observe('ciphertext_roundtrip', lambda: self.ciphertext(name))
        snapshot = self.snapshot(name)
        observation.update(snapshot_sha256=digest(snapshot), rows=len(snapshot['rows']), text_rows=len(snapshot['text']))
        observe('runtime_acl', lambda: require(snapshot['runtime'] == EXPECTED_ACL, 'runtime_privilege_contract'))
        observe('runtime_ddl_denial', lambda: self.denied(name, 'CREATE TABLE user_service.forbidden(id integer);', '42501'))
        observe('hub_denial', lambda: self.denied(name, 'SELECT * FROM hub_data.fixture;', '42501'))
        observe('admin_denial', lambda: self.denied(name, 'SELECT * FROM admin_control.fixture;', '42501'))
        observe('ciphertext_wrong_key_denial', lambda: self.denied(name,
            "SELECT pgp_sym_decrypt(sealed,'wrong-public-fixture-key') FROM user_service.fixture LIMIT 1;", '39000'))
        observe('ciphertext_tamper_denial', lambda: self.denied(name,
            "SELECT pgp_sym_decrypt(set_byte(sealed,octet_length(sealed)-1,get_byte(sealed,octet_length(sealed)-1)#1),'map-public-fixture-key') FROM user_service.fixture LIMIT 1;", '39000'))
        observe('unique_constraint', lambda: self.denied(name, "BEGIN; INSERT INTO user_service.collation_fixture VALUES(9000,'가','old'); ROLLBACK;", '23505'))
        observe('negative_probes_preserve_rows', lambda: require(self.snapshot(name) == snapshot, 'negative_probe_mutated_rows'))
        collation = observe('btree_sequential_queries', lambda: self.collation(name))
        (self.output / (label + '-synthetic.json')).write_text(json.dumps({'snapshot': snapshot, 'collation': collation}, ensure_ascii=False, indent=2) + '\n')
        observation['collation_sha256'] = digest(collation)
        return snapshot, collation, meta

    def restore(self, name, dump):
        self.run(['docker', 'exec', '-i', name, 'pg_restore', '--exit-on-error', '-h', '127.0.0.1', '-U', 'postgres', '-d', 'fixture'], input=dump, timeout=180)

    def dump(self, name, label):
        data = self.run(['docker', 'exec', name, 'pg_dump', '-Fc', '-h', '127.0.0.1', '-U', 'postgres', '-d', 'fixture'], timeout=180).stdout
        require(data.startswith(b'PGDMP'), 'custom_dump_expected')
        path = self.output / (label + '.dump')
        with path.open('xb') as handle:
            handle.write(data)
        self.backups[label] = {'path': path.name, 'bytes': len(data), 'sha256': hashlib.sha256(data).hexdigest(), 'retained': True}
        return data

    def cleanup(self):
        outcomes = {}
        for name in reversed(self.containers):
            try:
                p = self.run(['docker', 'inspect', name], accepted=(0, 1))
                if p.returncode == 1:
                    # Do not mistake arbitrary daemon/permission failures for successful deletion.
                    require(b'No such object:' in p.stderr, 'cleanup_inspect_failed')
                    outcomes[name] = 'NOT_FOUND'
                    continue
                actual = json.loads(p.stdout)[0]
                require(actual['Config'].get('Labels', {}).get('map.infra.fixture') == self.token, 'cleanup_ownership_mismatch')
                self.stop(name)
                self.run(['docker', 'rm', name])
                outcomes[name] = 'PASS'
            except Exception as error:
                outcomes[name] = 'FAIL:' + type(error).__name__
        for volume in reversed(self.volumes):
            try:
                actual = json.loads(self.run(['docker', 'volume', 'inspect', volume]).stdout)[0]
                require(actual.get('Labels', {}).get('map.infra.fixture') == self.token, 'volume_cleanup_ownership_mismatch')
                self.run(['docker', 'volume', 'rm', volume])
                outcomes[volume] = 'PASS'
            except Exception as error:
                outcomes[volume] = 'FAIL:' + type(error).__name__
        return outcomes

    def diagnostics(self):
        logs = {}
        for name in self.containers:
            try:
                actual = json.loads(self.run(['docker', 'inspect', name]).stdout)[0]
                require(actual['Config'].get('Labels', {}).get('map.infra.fixture') == self.token, 'diagnostic_owner_mismatch')
                p = self.run(['docker', 'logs', '--tail', '60', name], accepted=(0, 1))
                logs[name] = {'synthetic_stdout': p.stdout.decode(errors='replace')[-4096:], 'synthetic_stderr': p.stderr.decode(errors='replace')[-4096:]}
            except Exception:
                logs[name] = {'status': 'UNAVAILABLE'}
        (self.output / 'synthetic-diagnostics.json').write_text(json.dumps({'failures': self.failures, 'logs': logs}, indent=2) + '\n')


def checked(result, fixture, name, action):
    try:
        value = action()
        result['checks'][name] = {'status': 'PASS'}
        return value
    except Exception as error:
        code = str(error) if isinstance(error, (ValueError, CommandFailure)) else 'fixture_execution_failed'
        result['checks'][name] = {'status': 'FAIL', 'failure_code': code, 'error_type': type(error).__name__}
        detail = getattr(error, 'diagnostic', None)
        if detail:
            fixture.failures.append({'check': name, **detail})
        return None


def record_comparison(result, label, before, after, *, old_cohort=False):
    comparison = compare_collation(before, after, old_cohort=old_cohort)
    result.setdefault('collation_comparisons', {})[label] = comparison
    unchanged = comparison['same_corpus'] and not any(comparison[k] for k in ('ordering_changed', 'range_membership_changed', 'equality_membership_changed'))
    result['checks'][label] = {'status': 'PASS' if unchanged else 'FAIL', 'failure_code': None if unchanged else 'synthetic_collation_semantics_changed'}


def execute(old, new, output):
    require(os.environ.get('GITHUB_ACTIONS') == 'true' and os.environ.get('RUNNER_ENVIRONMENT') == 'github-hosted' and sys.platform == 'linux', 'remote_hosted_ci_only')
    require(re.fullmatch(r'[a-z0-9/_-]+@sha256:[a-f0-9]{64}', old), 'immutable_old_image_required')
    require(re.fullmatch(r'sha256:[a-f0-9]{64}', new) or re.fullmatch(r'[a-z0-9/_-]+@sha256:[a-f0-9]{64}', new), 'immutable_new_image_required')
    require(not output.exists(), 'fresh_output_required')
    output.mkdir(parents=True)
    fixture = Fixture(output)
    result = {'schema_version': 3, 'service': 'postgres', 'status': 'FAIL', 'old_image': old, 'new_image': new,
              'fixture_source_sha256': hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
              'synthetic_only': True, 'production_credentials_or_data_used': False,
              'physical_existing_volume_reuse_tested': False, 'production_collation_compatibility_verified': False,
              'safe_rollback_contract': 'After new writes use verified post-upgrade logical restore to a fresh old-version volume; pre-upgrade backup is disaster recovery with an explicit data-loss boundary only; never reuse migrated live PGDATA',
              'ciphertext_configured_algorithm': 'aes256 (fixed pgp_sym_encrypt options; pgp_key_id reports symmetric packet only)',
              'ciphertext_contract': 'Synthetic pgcrypto AES256 PGP ciphertext; exact bytes preserved and decrypt verified at every phase; not production key or application cipher proof',
              'resource_budget': {'max_running_containers': 1, 'total_created_containers': 4, 'max_existing_containers': 2, 'cpu_per_container': 1, 'memory_mib_per_container': 768, 'pids_per_container': 128, 'log_bytes_per_container': 30*1024**2, 'data_volumes': 'explicit labelled synthetic only', 'ttl_minutes': 150},
              'checks': {name: {'status': 'NOT_RUN'} for name in PHASES}}
    state = {}
    try:
        def baseline():
            name = fixture.start(old, 'old')
            fixture.sql(name, SEED + text_insert(OLD_TEXT, 'old', 0))
            snap, col, meta = fixture.probe(name, 'old', 'baseline', result)
            require(len(snap['rows']) == 1 and len(snap['text']) == len(OLD_TEXT), 'baseline_corpus_size')
            state.update(old_snapshot=snap, old_collation=col, old_meta=meta)
            state['old_dump'] = fixture.dump(name, 'pre-upgrade')
            fixture.retire(name)
        checked(result, fixture, 'baseline', baseline)

        def forward():
            name = fixture.start(new, 'new')
            state['forward'] = name
            fixture.restore(name, state['old_dump'])
            snap, col, meta = fixture.probe(name, 'new', 'forward-restored', result)
            require(snap == state['old_snapshot'], 'forward_rows_bytes_owners_acl_mismatch')
            require(meta['owners'] == state['old_meta']['owners'], 'forward_data_owner_mode_changed')
            record_comparison(result, 'forward_collation_unchanged', state['old_collation'], col)
            result['glibc_changed'] = meta['glibc'] != state['old_meta']['glibc']
            result['collation_provider_version_changed'] = meta['actual_collation_version'] != state['old_meta']['actual_collation_version']
        if 'old_dump' in state:
            checked(result, fixture, 'forward_restore', forward)

        def write_new():
            name = state['forward']
            fixture.sql(name, "INSERT INTO user_service.fixture(payload,location,captured_at,sealed) VALUES ('{\"synthetic\":true,\"stage\":\"new\"}',ST_SetSRID(ST_MakePoint(1,1),4326),'2026-01-02T00:00:00Z',pgp_sym_encrypt('map-synthetic-new','map-public-fixture-key','cipher-algo=aes256,compress-algo=0'));" + text_insert(NEW_TEXT, 'new', 100), user='map_runtime')
            snap, col, meta = fixture.probe(name, 'new', 'new-written', result)
            require(len(snap['rows']) == 2 and len(snap['text']) == len(OLD_TEXT) + len(NEW_TEXT), 'forward_write_missing')
            require(snap['rows'][:len(state['old_snapshot']['rows'])] == state['old_snapshot']['rows'], 'new_write_modified_old_ciphertext_rows')
            require([r for r in snap['text'] if r['stage'] == 'old'] == state['old_snapshot']['text'], 'new_write_modified_old_corpus')
            state.update(new_snapshot=snap, new_collation=col, new_meta=meta)
            record_comparison(result, 'old_cohort_after_new_write', state['old_collation'], col, old_cohort=True)
        if result['checks']['forward_restore']['status'] == 'PASS':
            checked(result, fixture, 'new_writes', write_new)

        def restart():
            name = state['forward']
            fixture.stop(name)
            fixture.run(['docker', 'start', name])
            fixture.ready(name, 'fixture')
            snap, col, meta = fixture.probe(name, 'new', 'candidate-restarted', result)
            require(snap == state['new_snapshot'], 'candidate_restart_lost_rows')
            require(meta['owners'] == state['new_meta']['owners'], 'candidate_restart_owner_changed')
            record_comparison(result, 'candidate_restart_collation_unchanged', state['new_collation'], col)
        if 'new_snapshot' in state:
            checked(result, fixture, 'candidate_restart', restart)

        def post_backup():
            state['new_dump'] = fixture.dump(state['forward'], 'post-upgrade')
            fixture.stop(state['forward'])
        if result['checks']['candidate_restart']['status'] == 'PASS':
            checked(result, fixture, 'post_upgrade_backup', post_backup)
        if 'forward' in state and result['checks']['post_upgrade_backup']['status'] != 'PASS':
            checked(result, fixture, 'candidate_stopped_after_failure', lambda: fixture.stop(state['forward']))

        # Both rollback paths are independent of the forward path's success. A
        # failed candidate restore must not suppress the old-backup recovery check.
        def old_backup_restore():
            name = fixture.start(old, 'old-backup')
            fixture.restore(name, state['old_dump'])
            snap, col, meta = fixture.probe(name, 'old', 'old-backup-restored', result)
            require(snap == state['old_snapshot'], 'pre_upgrade_backup_rollback_mismatch')
            require(meta['owners'] == state['old_meta']['owners'], 'old_backup_owner_changed')
            record_comparison(result, 'old_backup_collation_unchanged', state['old_collation'], col)
            fixture.retire(name)
        if 'old_dump' in state:
            checked(result, fixture, 'old_pre_upgrade_backup_restore', old_backup_restore)

        def post_new_restore():
            name = fixture.start(old, 'new-data-old')
            fixture.restore(name, state['new_dump'])
            snap, col, meta = fixture.probe(name, 'old', 'post-new-logical-old', result)
            require(snap == state['new_snapshot'], 'post_upgrade_dump_old_restore_mismatch')
            require(meta['owners'] == state['old_meta']['owners'], 'post_new_old_owner_changed')
            record_comparison(result, 'post_new_old_collation_unchanged', state['new_collation'], col)
            fixture.retire(name)
        if 'new_dump' in state:
            checked(result, fixture, 'old_post_upgrade_logical_restore', post_new_restore)

        def backup_integrity():
            require(bool(fixture.backups), 'no_retained_backup')
            for backup in fixture.backups.values():
                data = (output / backup['path']).read_bytes()
                require(len(data) == backup['bytes'] and hashlib.sha256(data).hexdigest() == backup['sha256'], 'retained_backup_modified')
        checked(result, fixture, 'retained_backup_integrity', backup_integrity)
        result['status'] = 'PASS' if all(c['status'] == 'PASS' for c in result['checks'].values()) else 'FAIL'
    finally:
        result['retained_backups'] = fixture.backups
        # Dumps and diagnostics remain in output on failure; only this sandbox's
        # labelled containers and their explicitly named synthetic volumes are removed.
        try:
            fixture.diagnostics()
            result['diagnostics'] = 'synthetic-diagnostics.json'
        except Exception:
            result['diagnostics'] = 'UNAVAILABLE'
        cleanup = fixture.cleanup()
        result['container_cleanup'] = cleanup
        result['cleanup'] = 'FAIL' if any(v.startswith('FAIL') for v in cleanup.values()) else 'PASS'
        if result['cleanup'] == 'FAIL':
            result['status'] = 'FAIL'
        (output / 'result.json').write_text(json.dumps(result, ensure_ascii=False, indent=2) + '\n')
    return result


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--old-image', required=True)
    p.add_argument('--new-image', required=True)
    p.add_argument('--output', required=True, type=Path)
    p.add_argument('--execute-ci', action='store_true')
    args = p.parse_args()
    if not args.execute_ci:
        print(json.dumps({'status': 'PLAN_ONLY', 'docker_calls': 0}))
        return 0
    result = execute(args.old_image, args.new_image, args.output)
    print(json.dumps({'status': result['status'], 'cleanup': result.get('cleanup')}))
    return 0 if result['status'] == 'PASS' else 1


if __name__ == '__main__':
    raise SystemExit(main())
