#!/usr/bin/env python3
"""Synthetic PG17/PostGIS3.5 logical forward/restore checks on hosted CI only."""
from __future__ import annotations
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import time
import uuid

ROLES = "CREATE ROLE map_owner NOLOGIN; CREATE ROLE map_runtime LOGIN; CREATE ROLE hub_owner NOLOGIN; CREATE ROLE admin_owner NOLOGIN;"
SEED = """
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
CREATE EXTENSION pgcrypto;
CREATE SCHEMA user_service AUTHORIZATION map_owner;
CREATE SCHEMA hub_data AUTHORIZATION hub_owner;
CREATE SCHEMA admin_control AUTHORIZATION admin_owner;
SET ROLE map_owner;
CREATE TABLE user_service.fixture (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, payload jsonb NOT NULL, location geometry(Point,4326), captured_at timestamptz NOT NULL, sealed bytea NOT NULL);
INSERT INTO user_service.fixture(payload,location,captured_at,sealed) VALUES ('{"synthetic":true,"stage":"old"}',ST_SetSRID(ST_MakePoint(0,0),4326),'2026-01-01T00:00:00Z',decode('01020304','hex'));
GRANT USAGE ON SCHEMA user_service TO map_runtime;
GRANT SELECT,INSERT,UPDATE ON user_service.fixture TO map_runtime;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA user_service TO map_runtime;
RESET ROLE;
SET ROLE hub_owner;
CREATE TABLE hub_data.fixture(id integer PRIMARY KEY, marker text NOT NULL);
INSERT INTO hub_data.fixture VALUES (1,'synthetic-hub');
RESET ROLE;
SET ROLE admin_owner;
CREATE TABLE admin_control.fixture(id integer PRIMARY KEY, marker text NOT NULL);
INSERT INTO admin_control.fixture VALUES (1,'synthetic-admin');
RESET ROLE;
"""
SNAPSHOT = """SELECT json_build_object(
 'rows',(SELECT json_agg(json_build_object('id',id,'payload',payload,'wkt',ST_AsEWKT(location),'captured_at',captured_at,'sealed',encode(sealed,'hex')) ORDER BY id) FROM user_service.fixture),
 'hub',(SELECT json_agg(row_to_json(x)) FROM (SELECT * FROM hub_data.fixture ORDER BY id) x),
 'admin',(SELECT json_agg(row_to_json(x)) FROM (SELECT * FROM admin_control.fixture ORDER BY id) x),
 'owners',(SELECT json_agg(row_to_json(x)) FROM (SELECT schemaname,tablename,tableowner FROM pg_tables WHERE schemaname IN ('user_service','hub_data','admin_control') ORDER BY schemaname,tablename) x),
 'runtime',(SELECT json_build_object('select',has_table_privilege('map_runtime','user_service.fixture','SELECT'),'insert',has_table_privilege('map_runtime','user_service.fixture','INSERT'),'schema_create',has_schema_privilege('map_runtime','user_service','CREATE'),'hub_schema',has_schema_privilege('map_runtime','hub_data','USAGE'),'admin_schema',has_schema_privilege('map_runtime','admin_control','USAGE')))
);"""


def require(value,message):
    if not value:raise ValueError(message)


class Fixture:
    def __init__(self,output):
        self.output=output;self.token=uuid.uuid4().hex[:12];self.containers=[]
    def run(self,args,*,input=None,accepted=(0,),timeout=120):
        p=subprocess.run(args,input=input,capture_output=True,timeout=timeout)
        require(p.returncode in accepted,'synthetic_command_failed:'+Path(args[0]).name)
        return p
    def sql(self,name,sql,*,database='fixture',user='postgres',accepted=(0,)):
        return self.run(['docker','exec','-i',name,'psql','-X','-qAt','-v','ON_ERROR_STOP=1','-v','VERBOSITY=sqlstate','-U',user,'-d',database],input=sql.encode(),accepted=accepted)
    def start(self,image,label):
        name='map-infra-pg-'+self.token+'-'+label
        self.run(['docker','run','-d','--name',name,'--label','map.infra.fixture='+self.token,'--network','none','--memory','768m','--cpus','1','-e','POSTGRES_HOST_AUTH_METHOD=trust','-e','POSTGRES_INITDB_ARGS=--locale=C --encoding=UTF8',image])
        self.containers.append(name)
        for _ in range(90):
            if self.sql(name,'SELECT 1;',database='postgres',accepted=(0,1,2)).returncode==0:break
            time.sleep(1)
        else:raise ValueError('postgres_readiness_timeout')
        self.sql(name,ROLES+'CREATE DATABASE fixture TEMPLATE template0;',database='postgres')
        return name
    def snapshot(self,name):
        return json.loads(self.sql(name,SNAPSHOT).stdout)
    def restore(self,name,dump):
        self.run(['docker','exec','-i',name,'pg_restore','--exit-on-error','-U','postgres','-d','fixture'],input=dump,timeout=180)
    def dump(self,name,label):
        b=self.run(['docker','exec',name,'pg_dump','-Fc','-U','postgres','-d','fixture'],timeout=180).stdout
        require(b.startswith(b'PGDMP'),'custom_dump_expected')
        p=self.output/(label+'.dump');p.write_bytes(b)
        return b,hashlib.sha256(b).hexdigest()
    def cleanup(self):
        for name in reversed(self.containers):
            actual=json.loads(self.run(['docker','inspect',name]).stdout)[0]
            require(actual['Config']['Labels'].get('map.infra.fixture')==self.token,'cleanup_ownership_mismatch')
            self.run(['docker','rm','-f','-v',name])


def execute(old,new,output):
    require(os.environ.get('GITHUB_ACTIONS')=='true' and os.environ.get('RUNNER_ENVIRONMENT')=='github-hosted' and sys.platform=='linux','remote_hosted_ci_only')
    require(re.fullmatch(r'[a-z0-9/_-]+@sha256:[a-f0-9]{64}',old),'immutable_old_image_required')
    require(re.fullmatch(r'sha256:[a-f0-9]{64}',new) or re.fullmatch(r'[a-z0-9/_-]+@sha256:[a-f0-9]{64}',new),'immutable_new_image_required')
    require(not output.exists(),'fresh_output_required');output.mkdir(parents=True)
    fixture=Fixture(output);result={'service':'postgres','status':'FAIL','old_image':old,'new_image':new,'synthetic_only':True,'production_credentials_or_data_used':False,'physical_existing_volume_reuse_tested':False,'production_collation_compatibility_verified':False,'safe_rollback_contract':'restore separately retained pre-upgrade logical backup; never reuse a migrated live volume','checks':{}}
    try:
        before=fixture.start(old,'old');fixture.sql(before,SEED)
        snapshot=fixture.snapshot(before);checks=result['checks']
        require(snapshot['runtime']=={'select':True,'insert':True,'schema_create':False,'hub_schema':False,'admin_schema':False},'baseline_runtime_acl')
        checks['old_synthetic_acl_and_rows']=True
        old_meta=json.loads(fixture.sql(before,"SELECT json_build_object('server',current_setting('server_version_num'),'postgis',postgis_lib_version(),'extensions',(SELECT json_object_agg(extname,extversion) FROM pg_extension),'encoding',current_setting('server_encoding'),'collation',(SELECT datcollate FROM pg_database WHERE datname=current_database()));").stdout)
        require(int(old_meta['server'])//10000==17 and old_meta['postgis'].startswith('3.5.'),'baseline_major_contract')
        data,checksum=fixture.dump(before,'pre-upgrade');result['pre_upgrade_dump_sha256']=checksum
        forward=fixture.start(new,'new');fixture.restore(forward,data)
        require(fixture.snapshot(forward)==snapshot,'forward_rows_owners_acl_mismatch');checks['forward_logical_restore_rows_owners_acl']=True
        new_meta=json.loads(fixture.sql(forward,"SELECT json_build_object('server',current_setting('server_version_num'),'postgis',postgis_lib_version(),'extensions',(SELECT json_object_agg(extname,extversion) FROM pg_extension),'encoding',current_setting('server_encoding'),'collation',(SELECT datcollate FROM pg_database WHERE datname=current_database()));").stdout)
        result['old_runtime']=old_meta;result['new_runtime']=new_meta
        require(170011<=int(new_meta['server'])<180000,'postgres_17_11_minimum_required')
        require(new_meta['postgis'].startswith('3.5.') and tuple(map(int,new_meta['postgis'].split('.'))) >= (3,5,7),'postgis_3_5_7_minimum_required')
        require(set(new_meta['extensions'])==set(old_meta['extensions']),'extension_set_changed')
        require(new_meta['encoding']==old_meta['encoding'] and new_meta['collation']==old_meta['collation'],'synthetic_locale_changed')
        owner=fixture.run(['docker','exec',forward,'stat','-c','%u:%g','/var/lib/postgresql/data']).stdout.decode().strip()
        uid=fixture.run(['docker','exec',forward,'id','-u','postgres']).stdout.decode().strip()
        gid=fixture.run(['docker','exec',forward,'id','-g','postgres']).stdout.decode().strip()
        require(owner=='999:999' and uid==gid=='999','data_uid_gid_changed');checks['data_owner_uid_gid_999']=True
        fixture.sql(forward,"INSERT INTO user_service.fixture(payload,location,captured_at,sealed) VALUES ('{\"synthetic\":true,\"stage\":\"new\"}',ST_SetSRID(ST_MakePoint(1,1),4326),'2026-01-02T00:00:00Z',decode('05060708','hex'));",user='map_runtime')
        denied=fixture.sql(forward,'CREATE TABLE user_service.forbidden(id integer);',user='map_runtime',accepted=(0,3))
        require(denied.returncode==3 and b'42501' in denied.stderr,'runtime_ddl_not_denied');checks['runtime_dml_and_ddl_denial']=True
        new_snapshot=fixture.snapshot(forward);require(len(new_snapshot['rows'])==2,'forward_write_missing')
        fixture.run(['docker','stop','--time','30',forward]);fixture.run(['docker','start',forward])
        for _ in range(60):
            if fixture.sql(forward,'SELECT 1;',accepted=(0,1,2)).returncode==0:break
            time.sleep(1)
        require(fixture.snapshot(forward)==new_snapshot,'candidate_restart_lost_rows');checks['candidate_restart_persistence']=True
        new_data,new_checksum=fixture.dump(forward,'post-upgrade');result['post_upgrade_dump_sha256']=new_checksum
        rollback=fixture.start(old,'rollback');fixture.restore(rollback,data)
        require(fixture.snapshot(rollback)==snapshot,'pre_upgrade_backup_rollback_mismatch');checks['old_image_pre_upgrade_backup_restore']=True
        postrollback=fixture.start(old,'new-data-old');fixture.restore(postrollback,new_data)
        require(fixture.snapshot(postrollback)==new_snapshot,'post_upgrade_dump_old_restore_mismatch');checks['old_image_new_dump_restore_synthetic']=True
        result['baseline_snapshot_sha256']=hashlib.sha256(json.dumps(snapshot,sort_keys=True).encode()).hexdigest()
        result['forward_snapshot_sha256']=hashlib.sha256(json.dumps(new_snapshot,sort_keys=True).encode()).hexdigest()
        result['status']='PASS'
    except Exception as error:
        result['error_type']=type(error).__name__;result['failure_code']=str(error) if isinstance(error,ValueError) else 'fixture_execution_failed'
    finally:
        try:fixture.cleanup();result['cleanup']='PASS'
        except Exception:result['cleanup']='FAIL';result['status']='FAIL'
        (output/'result.json').write_text(json.dumps(result,indent=2)+'\n')
    return result


def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--old-image',required=True);p.add_argument('--new-image',required=True);p.add_argument('--output',required=True,type=Path);p.add_argument('--execute-ci',action='store_true');a=p.parse_args()
    if not a.execute_ci:print(json.dumps({'status':'PLAN_ONLY','docker_calls':0}));return 0
    r=execute(a.old_image,a.new_image,a.output);print(json.dumps({'status':r['status'],'cleanup':r.get('cleanup')}));return 0 if r['status']=='PASS' else 1

if __name__=='__main__':raise SystemExit(main())
