import copy
import datetime as dt
import fcntl
import gzip
import importlib.util
import json
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location("ncp_prod_backup", ROOT / "scripts/ncp-production-backup.py")
job = importlib.util.module_from_spec(spec)
spec.loader.exec_module(job)


def config():
    return {"schema_version": 1, "environment": "prod", "project": "map-prod", "enrollment_sha256": "e" * 64,
            "postgres": {"container_id": "a" * 64, "image_id": "sha256:" + "b" * 64,
                         "user": "postgres", "database": "map_prod"},
            "redis": {"container_id": "c" * 64, "image_id": "sha256:" + "d" * 64},
            "remote": "s3://fixture-backups/prod/isolated", "age_recipient": "age1" + "q" * 58}


class FixtureBackend:
    """Only generated bytes and metadata: no Docker, database, age, or network."""
    def __init__(self):
        self.events = []
        self.fail_host = False
        self.corrupt_receipt = False

    def verify_host(self, value):
        self.events.append("verify_host")
        if self.fail_host:
            raise job.transfer.BackupError("synthetic_host_mismatch")

    def source(self, value, service):
        self.events.append("source_" + service)
        return {"Id": value[service]["container_id"], "Image": value[service]["image_id"]}

    def collect(self, kind, value, item, directory):
        self.events.append("collect_" + kind)
        names = ("map-prod.roles.sql.gz", "map-prod.sql.gz") if kind == "pg" else ("snapshot.rdb",)
        for name in names:
            job.transfer.write_bytes(directory / name, b"synthetic fixture bytes")
        files = [{"name": name, "sha256": job.transfer.digest(directory / name)} for name in names]
        now = dt.datetime.now(dt.timezone.utc)
        if kind == "pg":
            helper = {"version": 1, "environment": "prod", "database": "map_prod", "roles_have_passwords": False,
                      "created_at": now.strftime("%Y%m%dT%H%M%SZ"), "files": files}
        else:
            helper = {"schema_version": 1, "kind": "redis-rdb", "environment": "prod", "snapshot_at": now.isoformat(),
                      "image_id": item["Image"], "primary_restore": {"rdb_check": "PASS"}, "files": files}
        path = directory / "fixture.helper.json"
        job.transfer.write_json(path, helper)
        return path

    def upload(self, snapshot, value, kind):
        self.events.append("mock_upload_" + kind)
        verified = job.transfer.verify(snapshot, "prod")[1]
        return {"role": "prod", "transport": "ncp-kr-age-encrypted",
                "remote": value["remote"] + "/" + kind + "/" + "f" * 32,
                "transport_sha256": "f" * 64, "ncp_remote_verified": not self.corrupt_receipt,
                "source_created_at": verified["source_created_at"], "database_restore_executed": False}


class ProductionBackupTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.root = Path(self.tmp.name).resolve()
        self.cfg = config()
        self.backend = FixtureBackend()

    def test_collected_postgres_bundle_is_accepted_by_existing_restore_reader(self):
        def dump(command, path):
            sql = ("CREATE ROLE map_user_runtime NOLOGIN;\n" if "pg_dumpall" in command else
                   "COPY user_service.sample (id) FROM stdin;\n1\n\\.\n")
            with gzip.open(path, "wt", encoding="utf-8") as stream:
                stream.write(sql)
            path.chmod(0o600)

        with patch.object(job.redis, "run", return_value="1"), patch.object(job.pg, "dump_gzip", side_effect=dump), \
                patch.object(job.pg, "bootstrap_role", return_value="postgres"):
            helper = job.Backend().collect("pg", self.cfg, {"Id": self.cfg["postgres"]["container_id"]}, self.root)
        metadata, paths = job.pg.verified_bundle(helper, "prod")
        self.assertEqual(len(paths), 2)
        self.assertEqual(metadata["table_row_counts"], {"user_service.sample": 1})
        self.assertFalse(metadata["roles_have_passwords"])
        self.assertEqual(metadata["source_bootstrap_role"], "postgres")

    def test_only_pinned_production_configuration_is_accepted(self):
        path = self.root / "config.json"
        job.transfer.write_json(path, self.cfg)
        self.assertEqual(job.configuration(path), self.cfg)
        for key, value in (("environment", "test"), ("project", "map-test"), ("enrollment_sha256", "unpinned"),
                           ("remote", "s3://fixture-backups/test/isolated"), ("age_recipient", "unverified")):
            bad = {**self.cfg, key: value}
            path.write_text(json.dumps(bad))
            with self.subTest(key=key), self.assertRaises(job.transfer.BackupError): job.configuration(path)
        for database in ("map_test", "postgres", "other_prod"):
            bad = copy.deepcopy(self.cfg); bad["postgres"]["database"] = database
            path.write_text(json.dumps(bad))
            with self.assertRaisesRegex(job.transfer.BackupError, "production_database_required"):
                job.configuration(path)

    def test_wrong_host_is_rejected_before_state_creation(self):
        self.backend.fail_host = True
        with self.assertRaises(job.transfer.BackupError):
            job.execute("pg", self.cfg, data=self.root, backend=self.backend)
        self.assertEqual(list(self.root.iterdir()), [])

    def test_pg_and_redis_closed_bundle_transport_receipts(self):
        for kind in ("pg", "redis"):
            with self.subTest(kind=kind):
                result = job.execute(kind, self.cfg, data=self.root, backend=self.backend)
                self.assertTrue(result["success"])
                self.assertFalse(result["rpo_1h_overdue"])
                self.assertEqual(result["transport_sha256"], "f" * 64)
        self.assertEqual(len(list((self.root / "deploy/backup-receipts").glob("*.json"))), 2)
        self.assertEqual(list((self.root / "backups").iterdir()), [])
        self.assertFalse(any("gcp" in event for event in self.backend.events))

    def test_incomplete_remote_receipt_cannot_replace_last_success(self):
        first = job.execute("pg", self.cfg, data=self.root, backend=self.backend)
        self.backend.corrupt_receipt = True
        with self.assertRaisesRegex(job.transfer.BackupError, "incomplete"):
            job.execute("pg", self.cfg, data=self.root, backend=self.backend)
        result = job.write_status(self.root / "deploy", "pg", "BACKUP_FAILED")
        self.assertFalse(result["success"])
        self.assertEqual(first["snapshot_at"], result["snapshot_at"])
        self.assertEqual(len(list((self.root / "backups").iterdir())), 1)

    def test_failed_jobs_are_preserved_and_block_before_another_collection(self):
        self.backend.corrupt_receipt = True
        for _ in range(4):
            with self.assertRaises(job.transfer.BackupError):
                job.execute("pg", self.cfg, data=self.root, backend=self.backend)
        count = self.backend.events.count("collect_pg")
        with self.assertRaisesRegex(job.transfer.BackupError, "failed_jobs_require_review"):
            job.execute("pg", self.cfg, data=self.root, backend=self.backend)
        self.assertEqual(self.backend.events.count("collect_pg"), count)
        self.assertEqual(len(list((self.root / "backups").iterdir())), 4)

    def test_success_cleanup_refuses_foreign_file_and_retains_every_plaintext_byte(self):
        original = self.backend.upload
        def upload(snapshot, value, kind):
            (snapshot.parent / "operator-notes").write_text("preserve")
            return original(snapshot, value, kind)
        self.backend.upload = upload
        with self.assertRaisesRegex(job.transfer.BackupError, "unknown_backup_output"):
            job.execute("pg", self.cfg, data=self.root, backend=self.backend)
        directory = next((self.root / "backups").iterdir())
        self.assertEqual((directory / "operator-notes").read_text(), "preserve")
        self.assertTrue((directory / "map-prod.sql.gz").exists())
        self.assertTrue((directory / "closed/map-prod.sql.gz").exists())

    def test_local_receipt_history_is_bounded_without_touching_other_files(self):
        state = job.private_directory(self.root / "deploy")
        receipt = {"ncp_remote_verified": True, "source_created_at": "2026-09-09T00:00:00+00:00"}
        for number in range(98):
            job.retain_receipt(state, "pg", f"{number:032x}", receipt)
        history = state / "backup-receipts"
        self.assertEqual(len(list(history.glob("pg-*.json"))), 96)
        foreign = history / "operator-evidence.txt"; foreign.write_text("preserve")
        job.retain_receipt(state, "pg", "f" * 32, receipt)
        self.assertEqual(foreign.read_text(), "preserve")

    def test_deployment_lock_defers_before_source_access(self):
        state = job.private_directory(self.root / "deploy")
        with job.lock_file(state / "deploy.lock") as lock:
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
            result = job.execute("redis", self.cfg, data=self.root, backend=self.backend, lock_wait=0)
        self.assertEqual(result["code"], "LOCK_BUSY")
        self.assertTrue(result["rpo_1h_overdue"])
        self.assertEqual(self.backend.events, ["verify_host"])

    def test_source_requires_exact_ids_images_and_production_labels(self):
        item = {"Id": self.cfg["postgres"]["container_id"], "Image": self.cfg["postgres"]["image_id"],
                "State": {"Running": True}, "HostConfig": {"Memory": 1024},
                "Config": {"Labels": {"com.docker.compose.project": "map-prod", "com.docker.compose.service": "postgres"}}}
        with patch.object(job.redis, "run", return_value=json.dumps(item)) as run:
            self.assertEqual(job.Backend().source(self.cfg, "postgres"), item)
            self.assertNotIn(".Env", run.call_args.args[0][3])
        for key in ("Id", "Image"):
            bad = copy.deepcopy(item); bad[key] = "wrong"
            with patch.object(job.redis, "run", return_value=json.dumps(bad)), self.assertRaises(job.transfer.BackupError):
                job.Backend().source(self.cfg, "postgres")
        item["Config"]["Labels"]["com.docker.compose.project"] = "map-test"
        with patch.object(job.redis, "run", return_value=json.dumps(item)), self.assertRaises(job.transfer.BackupError):
            job.Backend().source(self.cfg, "postgres")

    def test_lock_symlinks_and_old_backups_are_preserved(self):
        state = job.private_directory(self.root / "deploy")
        target = self.root / "preserve"
        target.write_text("existing user data")
        (state / "deploy.lock").symlink_to(target)
        with self.assertRaises(job.transfer.BackupError):
            job.execute("pg", self.cfg, data=self.root, backend=self.backend)
        self.assertEqual(target.read_text(), "existing user data")


if __name__ == "__main__":
    unittest.main()
